### ISSUE TITLE
Availability/stock in PDP

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#115]
- [ ] display "Available" if stock of the product is > 0

**Comment by schleichardt** [comment]
@trangng For the demo data, what do we use for stock? Do we disable stock?
Do we use a big stock like 1000000000 elements?
Should we have products out of stock in the demo data? How much?
Should the availability information included in the product csv? Maybe this is too much effort and the availability data can be generated.

**Comment by schleichardt** [comment]
@trangng Is this an MVP feature?

**Comment by schleichardt** [comment]
> if a product is on stock, the customer is able to see a green symbol with the information that the product is available and it can be delivered in 2-5 days

**Comment by butenkor** [comment]
I think there are 2 topics (ability to add to cart and availability info) mixed together. If product is on stock then we show "add to cart button" if not we disable it and show availability info based on ```expectedDelivery``` and ```restockableInDays``` values.
http://dev.sphere.io/http-api-projects-inventory.html#inventory-entry

@trangng Could you check this?

**Comment by lauraluiz** [comment]
Done :)
