### ISSUE TITLE
Onboarding manual with SBT launcher script

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#13]

**Comment by lauraluiz** [comment]
@schleichardt what was this exactly?

**Comment by schleichardt** [comment]
the script checked in so you can run it with `./sbt run`

**Comment by lauraluiz** [comment]
Okay, then it would me more a starter project issue. But I wonder, is not enough with the activator? That's why we have it. We already say "if you have sbt, then do this, otherwise activator". Do we need so many options? Because it can get confusing.

**Comment by schleichardt** [comment]
yes, let's stick with activator since it also supports Windows

**Comment by lauraluiz** [comment]
OK! Then I will close this one :)
