### ISSUE TITLE
Missing deployment documentation

### ISSUE THREAD

**Issue by onibox** [commercetools/commercetools-sunrise-java#148]
The README references some 'activator' script that is not part of the repository.
And beside deploying to Heroku there is no description of how to deploy the app to a self-hosted server.

**Comment by lauraluiz** [comment]
@schleichardt do we want to re-enable the activator or remove it completely?

**Comment by schleichardt** [comment]
re-enable would be nice

**Comment by lauraluiz** [comment]
Would you mind doing it yourself?

**Comment by schleichardt** [comment]
Ok https://github.com/sphereio/sphere-sunrise/issues/149

**Comment by lauraluiz** [comment]
Thanks :)

**Comment by schleichardt** [comment]
Refer to Play deployment documentation

**Comment by schleichardt** [comment]
so should point in the readme to https://www.playframework.com/documentation/2.5.x/Deploying

**Comment by lauraluiz** [comment]
https://github.com/commercetools/commercetools-sunrise-java-starter is now the place for that. It contains already some of the fixes and the rest should be as issues.
