### ISSUE TITLE
Make version or Git sha visible

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#158]
@lauraluiz Should we include sth visible or invisible (HTML comment) into the template or should we generate some headers or an endpoint to get the version deployed?

**Comment by lauraluiz** [comment]
Yes, we will need it. So far we were having this version.txt that was easy to modify and check. We can also ask ops guys, they will be interested on it, I guess :)

**Comment by schleichardt** [comment]
@svenmueller What do you suggest here?

**Comment by svenmueller** [comment]
how about having the following routes (similar to the sphere components):

`/version`
```
{
  "version" : "0.1.0-SNAPSHOT-20150819122742",
  "build" : {
    "date" : "2015-08-19T12:28:09+0000",
    "number" : "2215",
    "gitCommit" : "d8c79e2eec180ec5b60c478df523818b60fdd6b4"
  }
}
```

`/health`
```
{
  "self" : {
    "healthy" : true
  }
}
```

**Comment by lauraluiz** [comment]
It looks good to me. Any objections?

**Comment by schleichardt** [comment]
no

**Comment by lauraluiz** [comment]
We should have everything already.
