### ISSUE TITLE
add counter to facets

### ISSUE THREAD

**Issue by trangng** [commercetools/commercetools-sunrise-java#177]
please add counter next to facets, so customer can see if he/she selects e.g. facet size 36 how many products would be shown on overview page. 

it should count the master variant, because we show master variants on the overview page

**Comment by lauraluiz** [comment]
Currently the platform counts variants and not products, that's why we removed them.
Until the platform supports it, we cannot implement it.

**Comment by trangng** [comment]
@lauraluiz yeah, that's ok. I'll put it in the backlog. But wanted to make sure the issue is there so we keep it in mind.

**Comment by lauraluiz** [comment]
Counts are actually there and configurable.
