### ISSUE TITLE
Handle invalid items in cart on change

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-java#252]
When the country/currency cart changes, some line items inside might not have prices for that context. The shop should remove those items and inform the customer.

**Comment by Oehmi** [comment]
@lauraluiz 
There was a recent change in the platform for handling invalid items when merging:
the relevant items will now be dropped and the recalculation will be executed with only the remaining items.

see https://dev.commercetools.com/release-notes.html#release-notes---commercetools-platform---version-release-17-october-2017

**Comment by lauraluiz** [comment]
Duplicated #577
