### ISSUE TITLE
Document how to deploy

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-java#301]
- [ ] with Heroku (+ configuration)
- [ ] configure it via application.conf
- [x] how to change template

**Comment by lauraluiz** [comment]
@stmeissner add anything you consider necessary

**Comment by stmeissner** [comment]
this should cover the important things

**Comment by lauraluiz** [comment]
Moved to starter project: https://github.com/commercetools/commercetools-sunrise-java-starter/issues/21
