### ISSUE TITLE
consider not using play.Logger anymore

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#308]
I think it is impractical to use play.Logger because you can neither spot easily where the log entry is coming from nor configure a special log level.

Also the play team has some concerns with it: https://github.com/playframework/playframework/issues/1669

I would prefer this:

``` java
//api from slf4j
private final static Logger logger = LoggerFactory.getLogger(MyClass.class);
```

**Comment by lauraluiz** [comment]
Yes, I wanted to remove the Play Logger long time ago, I don't use it in some new classes (e.g. `WebjarsFilesCopier`). But as it's so invasive I couldn't find a moment to do it.

**Comment by lauraluiz** [comment]
I did a quick search and I think it's not used anymore.
