### ISSUE TITLE
Find a better way to handle sessions

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-java#309]
E.g. some sessions are dependent from each other (customer -> cart). And they usually belong to different modules.
- Think frameworky.
- How to deal with dependent info (logout removes cart & customer).

**Comment by schleichardt** [comment]
CartSessionUtils is evil, it uses an injectionless factory

**Comment by lauraluiz** [comment]
It needs to:
- Customize info saved besides ID (e.g. name, email...)
- Allow to specify session key used

In general, think of customer vs driver situation. You would like to use the same interface with different implementations for both.
