### ISSUE TITLE
Send account mails (reset password, registration)

### ISSUE THREAD

**Issue by mmoelli** [commercetools/commercetools-sunrise-java#318]
- [ ] Registration: http://sphereio.github.io/commercetools-sunrise-theme/site/en/registration-email.html
- [ ] Password reset: http://sphereio.github.io/commercetools-sunrise-theme/site/en/password-reset-email.html

**Comment by lauraluiz** [comment]
Better to have an external system in charge of that, otherwise duplicated code between different apps (web app, iOS app...).

**Comment by lauraluiz** [comment]
For reset: https://github.com/commercetools/commercetools-sunrise-java/issues/532
