### ISSUE TITLE
Create a guest customer account when using guest checkout 

### ISSUE THREAD

**Issue by mmoelli** [commercetools/commercetools-sunrise-java#337]
In some cases, depending systems require a customer account to be attached to an order (e.g. SAPByDesign).

For such cases I would like to have the possibility to automatically create a guest customer account before the order is created. In order to avoid duplicates with the same mail (first order with guest checkout, later create real customer account), the email addresses for the guest accounts should get suffix "_guest", e.g. "example@test.com_guest"

**Comment by nkuehn** [comment]
@mmoelli would this be default?  

In general, I feel that this is rather a bug / feature gap in the SAP integration than a SUNRISE best practice recommendation (Cart & Order have all relevant customer integration and an integration should rather generate the necessary placeholder / customer facade and not the web frontend  ->  if that logic is in the web frontend it is not cross-channel any more.

**Comment by mmoelli** [comment]
@nkuehn I would not enable this behaviour by default, but it should be triggered via config file. 

Indeed we delegate some logic here to the frontend, but we decided that we do not want to have this logic in the adapter.

**Comment by nkuehn** [comment]
@mmoelli OK, thanks for the info. I nevertheless have a pretty bad feeling about it. 

BTW:  you may need to define the email pattern for followup guest orders with the same email address (otherwise a de facto account would be created, which could bring up a bunch of other issues).

**Comment by lauraluiz** [comment]
@mmoelli is this still a requirement? This behaviour should be very easy to execute on the project code instead of Sunrise.

**Comment by mmoelli** [comment]
no, not at the moment.
