### ISSUE TITLE
Hide empty categories

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-sunrise-java#351]
A common feature request is that the storefront must never show categories that contain no products (unless they are "dynamic" like sales). It's not about manually activating / deactivating categories but about an additional automatism. 

The core API does not directly support the case, but it would be great if the SUNRISE implementation would provide a best practice suggestion on how to implement the requirement (nearly all projects will have to cover it some way). 

A relatively "cheap" way to find out could be a facets only search on the category ID.  But the limitation in number of facets returned is a bit unclear and intransparent.

**Comment by lauraluiz** [comment]
Yes, unfortunately that wouldn't work for more than 200 categories (which is very low) and there is no way to paginate them. 

But we can enable an option to create a subtree of the original category tree without the empty categories, to replace the current cached category tree. It won't be updated until you refresh the cached categories, which currently is only on restart or the categories/refresh endpoint.

**Comment by nkuehn** [comment]
200 because of the faceting limit?  
you can actually "paginate",  but it's a bit of a hack ( smaller / greater than on the ID  or similar). 

Maybe research the new GraphQL based Category full text search?  The MC uses it for exactly that case (already showing the number of products in the category navigation.

**Comment by lauraluiz** [comment]
How does the pagination exactly work? If you specify a range in your facet expression you are going to get range stats instead of terms stats which won't help you to find out if your category has product or not.

Right now I'm not filtering out categories when the term stats contains "others", so when the 200 limit has been reached. I will definitely try the GraphQL option, great idea!

**Comment by nkuehn** [comment]
I would follow the graphQL option first, too. 

Doing the counting via "pagination" is really workaroundy and it may even be that it does not work for categories like it was sketched for brands once (which are a product attribute).  It would probably not work because a product can be in multiple categories, so you are not sure to get < 200 category facets just because you filtered the search query to a category ID range that is 200 categories. 

Anyhow,  I agree that GraphQL is the right way to go here.
