### ISSUE TITLE
SBT task to import theme

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-java#354]

**Comment by lauraluiz** [comment]
Cannot access the folders from within this particular JAR, need to take further look into it to find out the reasons.

**Comment by schleichardt** [comment]
as a workaround you can put the stuff as one zip file into the jar

**Comment by lauraluiz** [comment]
Moved and solved to https://github.com/commercetools/commercetools-sunrise-java-theme-importer
