### ISSUE TITLE
Release framework to Maven Central

### ISSUE THREAD

**Issue by mmoelli** [commercetools/commercetools-sunrise-java#369]

**Comment by schleichardt** [comment]
What is meant by this issue?

**Comment by lauraluiz** [comment]
Currently it is just released in Github but not to any remote repository from where you can use it as a dependency in your project.

**Comment by schleichardt** [comment]
What is "it"?

**Comment by lauraluiz** [comment]
Sunrise

**Comment by schleichardt** [comment]
So a better description is publish Sunrise (Framework?) JAR to repo (like MavenCentral/Bintray)?

**Comment by lauraluiz** [comment]
Yes, it was a short description meant to be detailed later.

**Comment by schleichardt** [comment]
We plan to achieve this next week.

**Comment by schleichardt** [comment]
done http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22commercetools-sunrise_2.11%22
