### ISSUE TITLE
MyAccount - Change password

### ISSUE THREAD

**Issue by mmoelli** [commercetools/commercetools-sunrise-java#395]

**Comment by fhaertig** [comment]
Just to check: Am I correct that there is already a template file for my-account-change-password, but the controller is missing and the HAL link is not present in PageMeta?

**Comment by lauraluiz** [comment]
@fhaertig yes, there is actually a template file for that, but we are missing all backend side (controllers, HAL Link, routes, etc.).

**Comment by selo-ecube** [comment]
Do you have plans to implement _change password_ (and also _reset password_) in the coming weeks? Or do you solely focus on stabilizing the framework instead?

**Comment by lauraluiz** [comment]
@selo-ecube second option: stabilizing the framework. Although once the backend code is stable we will work on stabilizing the Theme and at the same time we will implement some backend functionality of the wishlist. But features that require both frontend and backend won't be in the roadmap until v1.0.0 is reached.
