### ISSUE TITLE
SBT plugin for copy template files

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#406]

**Comment by schleichardt** [comment]
@lauraluiz I think that is done as we used it in the training.

**Comment by schleichardt** [comment]
no, on second though it needs to be published as SBT plugin

**Comment by lauraluiz** [comment]
Yep

**Comment by lauraluiz** [comment]
Done 🎉 
https://github.com/commercetools/commercetools-sunrise-java-theme-importer
