### ISSUE TITLE
Job for Category and ProductType autorefresh

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#407]
@butenkor suggested that it would be nice to set a intervall in application.conf when the shop should refresh the categories and product types

So it would be like a cronjob.

**Comment by lauraluiz** [comment]
@butenkor the current solution that I'm implementing caches the category tree and sets an expiration time in seconds, which can be configured in application.conf. Is that what you were looking for or rather  being able to decide a refresh time e.g. at 12am every night?
