### ISSUE TITLE
Improve load time of POP

### ISSUE THREAD

**Issue by rzenner** [commercetools/commercetools-sunrise-java#409]
At the moment, it takes > 20 seconds to load a POP on the iPad - during load, a half-rendered page is shown. This is the entry-point for the demo, so it's important to speed this up considerably.

**Comment by schleichardt** [comment]
@lauraluiz how do want we measure the page speed?
Can we pic a POP (a category?) and write how much time it takes now?

**Comment by lauraluiz** [comment]
Currently addressed by improving images. Please @rzenner let us know when the images and fixed and it needs to be adapted in Sunrise.

**Comment by lauraluiz** [comment]
Duplicated in https://github.com/commercetools/commercetools-sunrise-java-demo/issues/5
Let's keep the other one for this issue.
