### ISSUE TITLE
Code quality style/best practices list

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#41]
see #37 
* Post Redirect Get http://www.codeproject.com/Tips/433399/PRG-Pattern-Post-Redirect-Get (basically F5 does not cause to resubmit a form)
* alt tags for all pictures?
* width and height attributes for sliders (speed/rendering/performance)

**Comment by lauraluiz** [comment]
@schleichardt because of the PRG pattern?

**Comment by schleichardt** [comment]
I don't know anymore.

**Comment by lauraluiz** [comment]
Okay, so let's follow the pattern. So far I cannot foresee any problems with it.

**Comment by schleichardt** [comment]
We it already/it is topic of the theme.
