### ISSUE TITLE
Missing Test

### ISSUE THREAD

**Issue by AndrewHK** [commercetools/commercetools-sunrise-java#422]
I am trying to create tests for my project, and I can't find enough tests to get an idea on how to properly do it.
This for example, needs way more tests : 
[SunriseProductRecommendationTest](https://github.com/commercetools/commercetools-sunrise-java/blob/master/common/test/common/suggestion/SunriseProductRecommendationTest.java)

Could you kindly implement it ?

**Comment by lauraluiz** [comment]
@AndrewHK check the branch we are working on now instead of master: https://github.com/commercetools/commercetools-sunrise-java/tree/request-scoped-dependency-injection. This is where the tests are, master is still not using the framework style.

**Comment by AndrewHK** [comment]
@lauraluiz , this branch doesn't exist for me

**Comment by schleichardt** [comment]
it is now merged to master

**Comment by lauraluiz** [comment]
Yes, just like 1 hours ago :D
Now you can check master again.

**Comment by AndrewHK** [comment]
Perfect 👍  thanks
