### ISSUE TITLE
Provide url in Sunrise which creates or returns an email html for given orderId

### ISSUE THREAD

**Issue by floriansattler** [commercetools/commercetools-sunrise-java#426]
There is a separate Project for a standard microservice / Job that listens to "order created" messages and triggers the order confirmation emails. The goal is to have this independent of the frontend so that it does not need to be implemented and maintained separately for SUNRISE based and other projects.

**Comment by lauraluiz** [comment]
@floriansattler which is what you need from Sunrise exactly? I could not understand what you require from it since the microservice is independent from Sunrise.

**Comment by floriansattler** [comment]
@lauraluiz @butenkor and dotSource will take care of implementing this in Sunrise. I will discuss it with him again to define the exact requirements for Sunrise.

**Comment by lauraluiz** [comment]
@floriansattler the idea behind the microservice is precisely that it becomes independent of Sunrise, thus it does not have to be implemented in Sunrise but elsewhere. I will close this issue.
