### ISSUE TITLE
Implement Payone in Sunrise 

### ISSUE THREAD

**Issue by floriansattler** [commercetools/commercetools-sunrise-java#427]
Task is to implement Payone in Sunrise.

**Comment by floriansattler** [comment]
Steps
1. Build a connector (needs to be generic so that it is not only Sunrise specific, but can also be reused for other projects) connector.jar
2. Which payment methods are available. Implement as config file or custom object.
3. Implement Payone Module in Demo Store for Payment in Checkout

How does the shop know what payment methods are available?
--> information will be provided by a config file or custom object

How much is hardcoded in Frontend?
--> abstract as much as possible on the Java side
--> what can't be abstracted needs to be documented
--> Javascript/HTML are frontend specific

Further information:
- create new payment object only if new transaction is triggered

@lauraluiz @MGA-dotSource will define Interface methods
@butenkor will provide information which are necessary for interface and what is exactly need in Payment/Checkout workflow (which data are necessary to create successful transaction for payment?)

**Comment by floriansattler** [comment]
@lauraluiz can you please assign this issue to @MGA-dotSource

**Comment by floriansattler** [comment]
We also need something like a switch/balancer in Sunrise. If the value of your cart is 0 Euro the order should directly be created and not be forwarded to the Payone Adapter.

Business case: You provide vouchers to your customer, because something went wrong at your last order. Customer orders something for 10 Euro and has a 20 Euro discount. In this case totalAmount in cart is 0 Euro and the customer shouldn't be forwarded to Payone.

**Comment by butenkor** [comment]
- Save Bankdata encypted with Blowfish. Payone adapter can already decrypt if secret key is configured

- On success URL check if cart is not already an order. If not create one. If already created just redirect to order confirmation page.

**Comment by lauraluiz** [comment]
I've created the payment repo, so please redirect this issue there: https://github.com/commercetools/commercetools-sunrise-java-payment/issues/1
