### ISSUE TITLE
missing CSRF token lets add to cart fail with 403

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#428]
If you start visiting a page that does not add a token and then add sth. to the cart an error appears

**Comment by schleichardt** [comment]
@lauraluiz how do we want to solve this?

**Comment by lauraluiz** [comment]
A page like in POP?

**Comment by schleichardt** [comment]
The thing is, in an online shop you may can insert from any page a product.

**Comment by schleichardt** [comment]
https://www.playframework.com/documentation/2.5.x/JavaCsrf

The global filter will add everywhere the token, but it also will require every form has a CSRF check.

**Comment by lauraluiz** [comment]
Ok so if the theme is not supporting it properly, then it will fail. So we have to decide whether to force it or not. Forcing wouldn't be a bad idea either.

**Comment by lauraluiz** [comment]
It is implemented with the `CRSFFilter`, enforced everywhere.
