### ISSUE TITLE
improve travis build by sharing .sbt and .ivy2 folder

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#433]
for the Javadoc publish thing everything needs to be loaded again

**Comment by lauraluiz** [comment]
@katmatt is this solved by your work on travis.yml?

**Comment by katmatt** [comment]
@lauraluiz When I understand Michael correctly and after taking a look at our current build logs: Yes, this issue is fixed by my work on our travis.yml 😉

**Comment by lauraluiz** [comment]
Great :) !
