### ISSUE TITLE
PageDataHook doesn't keep Http Context

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-java#444]
`PageDataHook#acceptPageData` doesn't seem to keep the HttpContext. Therefore if you use injector to get the instance of a RequestScoped class, it will fail.

**Comment by schleichardt** [comment]
I guess it is a missing "Apply" and "currentContext()" here: https://github.com/commercetools/commercetools-sunrise-java/blob/master/common/app/com/commercetools/sunrise/common/controllers/SunriseFrameworkController.java#L141
