### ISSUE TITLE
include JavaMoney library fix

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#451]

**Comment by schleichardt** [comment]
see also https://github.com/commercetools/commercetools-sunrise-java/issues/446

**Comment by schleichardt** [comment]
build a JVM SDK helper

**Comment by schleichardt** [comment]
see also https://github.com/commercetools/commercetools-sunrise-java/pull/441/files

**Comment by lauraluiz** [comment]
Provided by the JVM SDK already. Additionally, we will investigate further the issue behind that.
