### ISSUE TITLE
SunriseRemoveAddressController.java: Authorization required

### ISSUE THREAD

**Issue by clearsky** [commercetools/commercetools-sunrise-java#467]
When removing an address there e.g http://localhost:9000/en/address/remove/J2Vyjzkw we receive a  message Unauthorized: You must be authenticated to access this page.

https://github.com/commercetools/commercetools-sunrise-java/blob/master/my-account/app/com/commercetools/sunrise/myaccount/addressbook/removeaddress/SunriseRemoveAddressController.java

**Comment by lauraluiz** [comment]
@clearsky that happens when the CSRF token is missing. Probably it is again something that is fixed in the app. Check you have this line in the theme: https://github.com/commercetools/commercetools-sunrise-java/blob/master/conf/templates/myaccount/my-address-book-address.hbs#L17

**Comment by clearsky** [comment]
Hi, the csrf token was missing and I've got it afterwards in the rendered page: 

   <a href="/en/address/remove/s1knC4CM">
      <input type="hidden" name="csrfToken" value="acd....."/>
      <img src="/assets/public/theme//img/delete-60px.png" alt="delete icon">
      Delete
    </a>

I've the 
* restarted the server
* logged out and in
but it does't help.

**Comment by lauraluiz** [comment]
Maybe you already checked, but can you inspect the HTML of the running app and make sure there's a hidden input field in the form and that this is filled with the corresponding token? If that's correct, I'm running out of options.

**Comment by clearsky** [comment]
I've updated my comment and set the html part as code now. Unfortunately we have the hidden field in the html code. It's not prio 1 topic, but we should store it in the backlog. thanks.

**Comment by lauraluiz** [comment]
@clearsky the problem is that I cannot reproduce it anywhere. You can try yourself to reproduce it with the staging system: http://sphere-sunrise.herokuapp.com/, which has master deployed. If you can't reproduce it, you can always wait until next release and use that one, which maybe contains the fix already (with this PR: https://github.com/commercetools/commercetools-sunrise-java/pull/463).

**Comment by lauraluiz** [comment]
If you still have issues with this, please let me know.
