### ISSUE TITLE
Provide setup for JS specs

### ISSUE THREAD

**Issue by emmenko** [commercetools/commercetools-sunrise-java#49]

**Comment by lauraluiz** [comment]
There is still no official sbt-jasmine... Only thing I found is this: https://github.com/joescii/sbt-jasmine-plugin

@emmenko @schleichardt any suggestions on this topic?

**Comment by schleichardt** [comment]
I still would say, let's go the default sbt-web way.

**Comment by emmenko** [comment]
`sbt-mocha` is ok.

**Comment by schleichardt** [comment]
It should be part of the theme not Sunrise Framework.
