### ISSUE TITLE
improve MultiControllerComponentResolver

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#490]
# \* currently the name is not intuitive
- it works only with concrete classes (return value)
  - does it make sense to return directly the initialized components instead of their classes?

**Comment by lauraluiz** [comment]
The resolver was dropped since v1.0.0-M1, because it was registering components on a non-explicit way, plus framework tags were not consistent.

Instead, ControllerComponentSuppliers were introduced.
