### ISSUE TITLE
version endpoint causes an exception

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#516]

**Comment by lauraluiz** [comment]
@schleichardt could you explain how to reproduce it? Otherwise it looks fine to me: https://demo.commercetools.com/version

**Comment by schleichardt** [comment]
was a demo issue and has been fixed with https://github.com/commercetools/commercetools-sunrise-java-demo/commit/62288f388861c10d52d4ca28d8cb97a3bd20332c and https://github.com/commercetools/commercetools-sunrise-java-demo/commit/ce4bc624c471fb905497701ccdf69907db7f9675
