### ISSUE TITLE
Cart can only hold about 4-6 items

### ISSUE THREAD

**Issue by shanezr** [commercetools/commercetools-sunrise-java#518]
If you add more than 6 items (depending on the variant data) you'll start getting a 503 on any further add-to-cart actions.

The MiniCart being stored in Http.Context.session is quite large, and eventually causes the Play session cookie value to be too large to be written back on the response.

**Comment by lauraluiz** [comment]
Thanks for reporting it, we have already brainstorming different ways to handle the mini cart without affecting performance.

**Comment by lauraluiz** [comment]
Fixed https://github.com/commercetools/commercetools-sunrise-java/pull/538
