### ISSUE TITLE
Unauthorized when adding to cart after following a link

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-sunrise-java#522]
When I open a browser tab for sunrise.commercetools.com and navigate to a pdp of a product, I can click the "Add to bag" button which will show the cart with that product added.

When I send a link to a product's pdp to someone else (or to myself and open it in another browser), clicking on "Add to bag" yields the following error:

```
Unauthorized
You must be authenticated to access this page.
```

We also encounter this issue in our project which is based on commercetools-sunrise-java.

I'm not sure whether this is related to #478.

**Comment by lauraluiz** [comment]
No, it's actually related to the CSRF token. Apparently when there's no open session the CSRF token is not generated. I'll take a look at it.
