### ISSUE TITLE
Use customerGroup pricing

### ISSUE THREAD

**Issue by mmoelli** [commercetools/commercetools-sunrise-java#54]

**Comment by lauraluiz** [comment]
@mmoelli do you mean to show the price according to the customer group?

**Comment by mmoelli** [comment]
indeed. So after login of a B2B customer different prices should be shown.

**Comment by nkuehn** [comment]
Isn't that done automatically be the platform?  Frontend just needs to make the cart the user's cart instead of leaving it like any other anoymous cart.

**Comment by mmoelli** [comment]
@nkuehn for the price selection in the cart it's correct. We are more focussing here on the display of prices on Product Overview pages.

**Comment by nkuehn** [comment]
ah, scoped price search.  Thanks!
