### ISSUE TITLE
SunriseFrameworkMyAccountController findCustomer improvement

### ISSUE THREAD

**Issue by fhaertig** [commercetools/commercetools-sunrise-java#549]
The SunriseFrameworkMyAccountController delegates the search of a Customer to the CustomerFinderBySession by using:
` injector().getInstance(CustomerFinderBySession.class).findCustomer(null);`

As far as I know, by that we are able to modify the logic for retrieving a customer only by extending CustomerFinderBySession. This doesn't fit our needs, so we would like to use our own implementation. This would require something like: `injector.getInstance(Key.get(Types.newParameterizedType(CustomerFinder.class, Void.class)));`

Would be nice if you could consider this.

UPDATE: I just realized that CustomerFinderBySession is final, so even extending wouldn't work.

**Comment by lauraluiz** [comment]
@fhaertig thanks for reporting it, it was not yet in the issues but still something considered.
As it is right now, all finders are not meant to be replaced by injection but simply by using your own. 

The method in `SunriseFrameworkMyAccountController` is just a syntactic sugar to access the customer in session easily (actually the method name should reflect that is by session). But I would like to provide a better way to access the customer in a global way (see https://github.com/commercetools/commercetools-sunrise-java/issues/524).

Thanks for your suggestion, I'll keep it in mind when I work with the [fetching](https://github.com/commercetools/commercetools-sunrise-java/labels/fetching) topic.

**Comment by lauraluiz** [comment]
Fixed in versions > v1.0.0-M1.
Now all resource finders require only the minimum and non-specific information, so that you can replace the way things are fetched by just replacing the binding.
See example: https://github.com/commercetools/commercetools-sunrise-java/blob/v1.0.0-M1.1/my-account/app/com/commercetools/sunrise/myaccount/CustomerFinder.java
