### ISSUE TITLE
Encode Querystring parameters

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-java#567]
In `QueryStringUtils` the parameters are not encoded.

**Comment by katmatt** [comment]
In the old release it's in UrlUtils.

**Comment by lauraluiz** [comment]
Fixed in https://github.com/commercetools/commercetools-sunrise-java/releases/tag/v0.17.0

**Comment by VasumathiJayakumar** [comment]
This was related to the request from ecube https://sphereio.uservoice.com/admin/tickets/1277
