### ISSUE TITLE
Facets: counting products instead of variants 

### ISSUE THREAD

**Issue by fhaertig** [commercetools/commercetools-sunrise-java#570]
As #177 states, it is possible to show the facet count in the shop. However, I couldn't find a way to use the [Counting Products](http://dev.commercetools.com/http-api-projects-products-search.html#counting-products) feature for a SelectFacet. TermFacetSearchModel offers a "withCountingProducts" method, but it sadly seems to be unused.

Maybe I'm missing something. Could you show us how to use this feature? In case it is currently not supported by sunrise, is it planned anytime soon?

Thanks in advance!

**Comment by lauraluiz** [comment]
@fhaertig yes you are right, the feature was implemented in the platform after the `Facet` classes in Sunrise were implemented and then it was not adapted to support it. I would like to support them within this month.

**Comment by lauraluiz** [comment]
https://github.com/commercetools/commercetools-sunrise-java/blob/master/move-to-sdk/app/io/sphere/sdk/facets/FacetOption.java#L88

**Comment by katmatt** [comment]
We first need to implement the above jvm sdk issue. Without this facet expression extension, the response for our `TermStats#productCount` will always be null. That's the reasion why this property is marked as optional.

**Comment by lauraluiz** [comment]
@fhaertig you'll find the fix in v0.18.0
