### ISSUE TITLE
Discussion of cached things

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#58]
@lauraluiz @hajoeichler 
I think we should load the following things at application start or first needed and load them not on every request they are needed
- Categories
- Customer Groups
- Product Types
- Shipping Methods
- Tax Categories
- Zones
- project info

**Comment by lauraluiz** [comment]
So we need a DI module that allows to fetch these entities at the startup and it needs to provide some kind of refresh. Triggering this refresh should also be accessible somehow from a browser, to avoid having to wait or restarting the application to see the changes.

**Comment by schleichardt** [comment]
I think we should extend the interfaces to have a reload method.

**Comment by schleichardt** [comment]
Or the put them into a wrapper object, which is easier to implement, but more verbose to use.

**Comment by lauraluiz** [comment]
Okay so the refresh logic will be provided by the JVM SDK, so Sunrise will take care of calling it and allow to call it from outside.

**Comment by schleichardt** [comment]
Does this look still understandable?

```
public ApplicationController(final Cached<CategoryTree> categoryTree) {
}
```

**Comment by schleichardt** [comment]
I think to resolve this with DI, 

```java
public ApplicationController(final CachedCategoryTree categoryTree) {
}
```

is better, which is a `Cached<CategoryTree>`.

**Comment by lauraluiz** [comment]
I think it's perfectly understandable, both of them, but yes the second one is better :+1:

**Comment by butenkor** [comment]
Seems confusing that developers have to deal with 2 types (CachedCategoryTree and CategoryTree) I would vote to have CategoryTree only and documentation should provide proper information what could / is cached and what not and how one can refresh it.

**Comment by lauraluiz** [comment]
I'll close this, since this is nicely implemented via injection. There are multiple issues under the "caching" label to improve it.
