### ISSUE TITLE
Fix I18n TODOs in pre-v1.0.0

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-sunrise-java#605]
We should add i18n for the `// TODO i18n` comments.

**Comment by katmatt** [comment]
Duplicates  #386

**Comment by Valerzen88** [comment]
Hello,
is any progress at that fix after 5 month? Our customer needs this to be changed in the next days...

Especially it should be changed in the following methods:

- SunriseSignUpController.handleClientErrorFailedAction()
- SunriseFrameworkController.saveUnexpectedFormError()
- SunriseLogInController.handleClientErrorFailedAction()

Regards,
Valeri

**Comment by lauraluiz** [comment]
solved https://github.com/commercetools/commercetools-sunrise-java/pull/684
