### ISSUE TITLE
Rename controller actions and controllers for cart

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-java#609]
As "Do something to cart" as opposed to the name of the CTP action name. As it is now it could be mistaken with any other shopping list.

**Comment by lauraluiz** [comment]
Current relation of namings:
WISHLIST NAMES  <->   CART NAMES
AddToWishlistController  <->  AddLineItemController
RemoveFromWishlistController  <->  RemoveLineItemController
MyWishlistController  <->   CartDetailController
N/A  <->  ChangeLineItemQuantityController

We need to find a proper way to name the controllers and related classes now that we have shopping lists. We have to focus on using flexible names that allow us to add new shopping lists in the future and a similar naming structure among all of them.

The wishlist current way of naming has the benefit that defines the "entity" being updated. Also the "my" prefix is a nice way to name the detail pages. The one controller always difficult to name is the change quantity. Should it be "ChangeQuantityInCartController"?

Following those lines, some possible names would be:

WISHLIST NAMES  <->   CART NAMES
AddToWishlistController  <->  AddToCartController
RemoveFromWishlistController  <->  RemoveFromCartController
MyWishlistController  <->   MyCartController
N/A  <->  ChangeQuantityInCartController

@katmatt @acbeni WDTY?

**Comment by katmatt** [comment]
I like your suggestion, but may be we should use `WishlistController` instead of `MyWishlistController`? And `CartController` instead of `MyCartController`?
