### ISSUE TITLE
Update JVM SDK to v.1.18.0

### ISSUE THREAD

**Issue by fhaertig** [commercetools/commercetools-sunrise-java#615]
We tried to update the commercetools JVM SDK from 1.13.0 to 1.18.0 in our shop. However, this conflicts with sunrise 1.19.0 due to the [breaking change in sdk version 1.16.0 ](http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/meta/ReleaseNotes.html#v1_16_0). Could you provide a  recompiled release using the 1.18.0 sdk? Otherwise we would not profit from the bugfixes in this version.

Thanks in advance!

**Comment by lauraluiz** [comment]
Thanks for reporting it, we'll try to keep version pre-1.0.0 up to date with the JVM SDK too :)
You should be able to use v0.20.0 within an hour:
https://github.com/commercetools/commercetools-sunrise-java/releases/tag/v0.20.0
