### ISSUE TITLE
Update JVM-SDK in v0.x

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-sunrise-java#637]
Could you provide a new v0.x release that uses JVM-SDK 1.21.0? Thanks!

**Comment by lauraluiz** [comment]
@selo-ecube you'll have available Sunrise's v0.21.0 with JVM SDK's v1.21.0 within an hour: https://github.com/commercetools/commercetools-sunrise-java/releases/tag/v0.21.0

Sorry we didn't provide it before, we were not aware that our latest release would cause binary breaking changes. Could you tell us the issue you had when overriding dependencies? This way next time we can detect it sooner and update Sunrise right after the JVM SDK release :)

**Comment by selo-ecube** [comment]
Thanks for the release! I'm not aware of any binary breaking changes. I inferred from https://github.com/commercetools/commercetools-sunrise-java/issues/615#issuecomment-307339729 that you'd want to update the dependency in sunrise-java anyways. We can also override the dependency locally next time and only ask for a release of sunrise-java if that fails. Sorry for the confusion!

**Comment by lauraluiz** [comment]
@selo-ecube sorry for the misunderstanding and thanks for the reminder! :)
We are working on improving the release process and try to link the SDK's with Sunrise's. But for now we at least try to make sure that Sunrise doesn't use a very old version like it happened before. Of course on binary breaking change that is immediately prioritized.
