### ISSUE TITLE
Will there be further updates to this project?

### ISSUE THREAD

**Issue by gitlui** [commercetools/commercetools-sunrise-java#706]
Hello there,
I was viewing the commit history and it seems to me, like this project ist not actively developed anymore.
I was considering to integrate the framework into our project and modify it from this point onwards directly.
Would you advise to not do so?

What's the plan with this project?

Kind regards

**Comment by skyriakou** [comment]
@gitlui The Sunrise Java Shop Framework is no longer maintained. If you would nevertheless like to use it for your own developments you should fork this repository under the given license and continue developing your version, but please be aware that there will be no more updates and no support provided to this framework.

**Comment by gitlui** [comment]
Thank you very much for the clarification.
I will do so :)
